<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'insegment\\notvalidregexpexception' => '/InSegment/NotValidRegexpException.php',
                'insegment\\notvalidruleexception' => '/InSegment/NotValidRuleException.php',
                'insegment\\replacer' => '/InSegment/Replacer.php',
                'insegment\\replacerfacade' => '/InSegment/ReplacerFacade.php',
                'insegment\\replacerule' => '/InSegment/ReplaceRule.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
